# Generated by Django 3.1.7 on 2021-03-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_userbookrelations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelations',
            name='bookmarks',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userbookrelations',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
