# Generated by Django 3.1.7 on 2021-03-28 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210329_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbookrelations',
            old_name='ratte',
            new_name='rate',
        ),
    ]
