# Generated by Django 3.1.7 on 2021-03-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210329_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
