# Generated by Django 3.1.7 on 2021-04-02 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0009_book_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='owner',
        ),
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ManyToManyField(null=True, related_name='my_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
