# Generated by Django 3.1.7 on 2021-04-02 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_auto_20210402_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='critic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='critic_book', to=settings.AUTH_USER_MODEL),
        ),
    ]
